name = "GeometricMedicalPhantoms"
uuid = "c297bd51-60f5-42e7-80e4-f985777cb71a"
version = "1.0.0"
authors = ["Tamas Hakkel <hakkelt@gmail.com>"]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[workspace]
projects = ["test", "benchmark", "docs"]

[compat]
PrecompileTools = "1"
julia = "1.10"
