name = "GeometricMedicalPhantoms"
uuid = "c297bd51-60f5-42e7-80e4-f985777cb71a"
version = "1.0.0-DEV"
authors = ["Tamas Hakkel <hakkelt@gmail.com>"]

[workspace]
projects = ["test", "benchmark"]

[compat]
julia = "1.10"
